name: ConjoinedPlugin
version: 1.2.0
main: me.crazybanana.conjoinedplugin.ConjoinedPlugin
api-version: 1.16
authors: [CrazyBanana]
description: Minecraft But 2 players control 1
commands:
  start:
    description: start
  interact:
    description: interact
  movement:
    description: movement
  forceend:
    description: forceend
